### ISSUE TITLE
Bevy 0.10

### ISSUE THREAD

**Issue by HexSleeves** [hakolao/bevy_vulkano#14]
Are there plans to migrate to bevy 0.10? Love the library!

**Comment by hakolao** [comment]
If there is enough interest, I could. However, I would not mind a PR if you wish to contribute!

**Comment by hakolao** [comment]
I started it but it was a bit larger than I expected so I needed to postpone. 😃

**Comment by HexSleeves** [comment]
Diving through it now I can definitely tell the hardest part will be migrating the window setup. Windows are now entities and they also removed some functionality like "WindowId" in favor of winit windowId

**Comment by HexSleeves** [comment]
I started the port on my main branch. I have most things ported, but I am a but confused on how you would like to handle some things

https://github.com/hakolao/bevy_vulkano/pull/15

**Comment by hakolao** [comment]
Done :)
