### ISSUE TITLE
capture rendered frames

### ISSUE THREAD

**Issue by cs50victor** [hakolao/bevy_vulkano#18]
Is there a way to capture rendered frames 'headlessly' using bevy_vulkano?

I'm currently capturing and sending frames like this https://github.com/cs50victor/kitt2/blob/main/lkgpt/src/main.rs#L2892

**Comment by hakolao** [comment]
By headlessly do you mean without a window? That is possible (similar to the windowless example).

i am not sure what benefit there is in this to your project, but this library aims to just give you access within bevy to do anything you like with Vulkano.

**Comment by cs50victor** [comment]
hey, thanks for the feedback.  Yes, by headless i meant without a window ( i.e on a server where the rendered frames are sent to the client ). I'm new to the bevy ecosystem but  I've been learning Vulkan using vulkano for a couple months. Would most other bevy plugins work with bevy_vulkano or would it require some extra work to stitch them together?

**Comment by hakolao** [comment]
Anything that is dependent on the bevy renderer won’t work. Which is quite many, but you should see it from the plugin dependencies.

**Comment by cs50victor** [comment]
ok, got it. Thanks @hakolao
